# tests.py
from django.urls import reverse
from rest_framework.test import APITestCase
from rest_framework import status
from io import StringIO
from django.core.files.uploadedfile import SimpleUploadedFile
from .models import User


class CSVUploadTestCase(APITestCase):

    def setUp(self):
        self.url = reverse('users-upload-csv')  # auto-generated by router

    def create_csv_file(self, content: str):
        return SimpleUploadedFile(
            "test.csv",
            content.encode('utf-8'),
            content_type="text/csv"
        )

    def test_valid_csv_upload(self):
        csv_content = """name,email,age
John Doe,john@test.com,25
Jane Doe,jane@test.com,30
"""
        file = self.create_csv_file(csv_content)

        response = self.client.post(self.url, {'file': file}, format='multipart')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['success_count'], 2)
        self.assertEqual(User.objects.count(), 2)

    def test_invalid_data(self):
        csv_content = """name,email,age
Invalid User,invalidemail,200
"""
        file = self.create_csv_file(csv_content)

        response = self.client.post(self.url, {'file': file}, format='multipart')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['rejected_count'], 1)
        self.assertEqual(User.objects.count(), 0)

    def test_duplicate_email(self):
        User.objects.create(name="Existing", email="dup@test.com", age=25)

        csv_content = """name,email,age
New User,dup@test.com,30
"""
        file = self.create_csv_file(csv_content)

        response = self.client.post(self.url, {'file': file}, format='multipart')

        self.assertEqual(response.status_code, status.HTTP_200_OK)
        self.assertEqual(response.data['rejected_count'], 1)
        self.assertEqual(User.objects.count(), 1)

    def test_invalid_file_type(self):
        file = SimpleUploadedFile("test.txt", b"invalid content")

        response = self.client.post(self.url, {'file': file}, format='multipart')

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)

    def test_no_file_uploaded(self):
        response = self.client.post(self.url, {}, format='multipart')

        self.assertEqual(response.status_code, status.HTTP_400_BAD_REQUEST)